schema_version: 1

context:
  name: python-libdiscid
  version: "2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a2d0a7773c2daf5b3d4727d84a5c7f6de9ecb5a9c1a9d53d667c20a76c0a6769

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: match(python, "<3.11")

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - cython >=3
    - python
    - setuptools >=43
    # - pkgconfig Is only an optional dependancy and happens to make the build fail
    - pip
    - libdiscid
  run:
    - python

tests:
  - python:
      imports:
        - libdiscid
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Python bindings for libdiscid
  license: MIT
  license_file: LICENSE
  description: python-libdiscid implements Python >= 3.6 bindings for libdiscid using Cython.
  homepage: https://github.com/sebastinas/python-libdiscid
  documentation: https://pythonhosted.org/python-libdiscid/

extra:
  recipe-maintainers:
    - HeavyTony2
